# Generated by Django 4.2.11 on 2024-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_ver', models.CharField(max_length=100)),
                ('hil_id', models.CharField(max_length=100)),
            ],
        ),
    ]
